name: Hello World
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
  speak:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"
  test:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install python-is-python3
      - run: sudo apt-get install pip
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: pip install -r requirements.txt
      - run: pytest
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install python-is-python3
      - run: sudo apt-get install pip
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: pip install -r requirements.txt
      - run: pylint *.py --fail-under 8