name: Hello World
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
  speak:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"
  test:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install python-is-python3
      - run: sudo apt-get install pip
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: pip install pytest
      - run: pytest